python train.py --index 0 3 --dataset cora --test-size 0.2 --k 2
python train.py --index 0 3 --dataset cora --test-size 0.2 --k 3
python train.py --index 0 3 --dataset cora --test-size 0.2 --k 4
python train.py --index 0 3 --dataset cora --test-size 0.2 --k 5
python train.py --index 0 3 --dataset cora --test-size 0.2 --k 6
python train.py --index 0 3 --dataset cora --test-size 0.2 --k 7
python train.py --index 0 3 --dataset cora --test-size 0.2 --k 8
python train.py --index 0 3 --dataset cora --test-size 0.2 --k 9
python train.py --index 0 3 --dataset cora --test-size 0.2 --k 10
python train.py --index 0 3 --dataset cora --test-size 0.4 --k 2
python train.py --index 0 3 --dataset cora --test-size 0.4 --k 3
python train.py --index 0 3 --dataset cora --test-size 0.4 --k 4
python train.py --index 0 3 --dataset cora --test-size 0.4 --k 5
python train.py --index 0 3 --dataset cora --test-size 0.4 --k 6
python train.py --index 0 3 --dataset cora --test-size 0.4 --k 7
python train.py --index 0 3 --dataset cora --test-size 0.4 --k 8
python train.py --index 0 3 --dataset cora --test-size 0.4 --k 9
python train.py --index 0 3 --dataset cora --test-size 0.4 --k 10
python train.py --index 0 3 --dataset cora --test-size 0.6 --k 2
python train.py --index 0 3 --dataset cora --test-size 0.6 --k 3
python train.py --index 0 3 --dataset cora --test-size 0.6 --k 4
python train.py --index 0 3 --dataset cora --test-size 0.6 --k 5
python train.py --index 0 3 --dataset cora --test-size 0.6 --k 6
python train.py --index 0 3 --dataset cora --test-size 0.6 --k 7
python train.py --index 0 3 --dataset cora --test-size 0.6 --k 8
python train.py --index 0 3 --dataset cora --test-size 0.6 --k 9
python train.py --index 0 3 --dataset cora --test-size 0.6 --k 10
python train.py --index 0 3 --dataset cora --test-size 0.8 --k 2
python train.py --index 0 3 --dataset cora --test-size 0.8 --k 3
python train.py --index 0 3 --dataset cora --test-size 0.8 --k 4
python train.py --index 0 3 --dataset cora --test-size 0.8 --k 5
python train.py --index 0 3 --dataset cora --test-size 0.8 --k 6
python train.py --index 0 3 --dataset cora --test-size 0.8 --k 7
python train.py --index 0 3 --dataset cora --test-size 0.8 --k 8
python train.py --index 0 3 --dataset cora --test-size 0.8 --k 9
python train.py --index 0 3 --dataset cora --test-size 0.8 --k 10
python train.py --index 0 3 --dataset citeseer --test-size 0.2 --k 2
python train.py --index 0 3 --dataset citeseet --test-size 0.2 --k 3
python train.py --index 0 3 --dataset citeseer --test-size 0.2 --k 4
python train.py --index 0 3 --dataset citeseer --test-size 0.2 --k 5
python train.py --index 0 3 --dataset citeseer --test-size 0.2 --k 6
python train.py --index 0 3 --dataset citeseer --test-size 0.2 --k 7
python train.py --index 0 3 --dataset citeseer --test-size 0.2 --k 8
python train.py --index 0 3 --dataset citeseer --test-size 0.2 --k 9
python train.py --index 0 3 --dataset citeseer --test-size 0.2 --k 10
python train.py --index 0 3 --dataset citeseer --test-size 0.4 --k 2
python train.py --index 0 3 --dataset citeseer --test-size 0.4 --k 3
python train.py --index 0 3 --dataset citeseer --test-size 0.4 --k 4
python train.py --index 0 3 --dataset citeseer --test-size 0.4 --k 5
python train.py --index 0 3 --dataset citeseer --test-size 0.4 --k 6
python train.py --index 0 3 --dataset citeseer --test-size 0.4 --k 7
python train.py --index 0 3 --dataset citeseer --test-size 0.4 --k 8
python train.py --index 0 3 --dataset citeseer --test-size 0.4 --k 9
python train.py --index 0 3 --dataset citeseer --test-size 0.4 --k 10
python train.py --index 0 3 --dataset citeseer --test-size 0.6 --k 2
python train.py --index 0 3 --dataset citeseer --test-size 0.6 --k 3
python train.py --index 0 3 --dataset citeseer --test-size 0.6 --k 4
python train.py --index 0 3 --dataset citeseer --test-size 0.6 --k 5
python train.py --index 0 3 --dataset citeseer --test-size 0.6 --k 6
python train.py --index 0 3 --dataset citeseer --test-size 0.6 --k 7
python train.py --index 0 3 --dataset citeseer --test-size 0.6 --k 8
python train.py --index 0 3 --dataset citeseer --test-size 0.6 --k 9
python train.py --index 0 3 --dataset citeseer --test-size 0.6 --k 10
python train.py --index 0 3 --dataset citeseer --test-size 0.8 --k 2
python train.py --index 0 3 --dataset citeseer --test-size 0.8 --k 3
python train.py --index 0 3 --dataset citeseer --test-size 0.8 --k 4
python train.py --index 0 3 --dataset citeseer --test-size 0.8 --k 5
python train.py --index 0 3 --dataset citeseer --test-size 0.8 --k 6
python train.py --index 0 3 --dataset citeseer --test-size 0.8 --k 7
python train.py --index 0 3 --dataset citeseer --test-size 0.8 --k 8
python train.py --index 0 3 --dataset citeseer --test-size 0.8 --k 9
python train.py --index 0 3 --dataset citeseer --test-size 0.8 --k 10
python train.py --index 0 3 --dataset BlogCatalog --test-size 0.2 --k 2
python train.py --index 0 3 --dataset BlogCatalog --test-size 0.2 --k 3
python train.py --index 0 3 --dataset BlogCatalog --test-size 0.2 --k 4
python train.py --index 0 3 --dataset BlogCatalog --test-size 0.2 --k 5
python train.py --index 0 3 --dataset BlogCatalog --test-size 0.2 --k 6
python train.py --index 0 3 --dataset BlogCatalog --test-size 0.2 --k 7
python train.py --index 0 3 --dataset BlogCatalog --test-size 0.2 --k 8
python train.py --index 0 3 --dataset BlogCatalog --test-size 0.2 --k 9
python train.py --index 0 3 --dataset BlogCatalog --test-size 0.2 --k 10
python train.py --index 0 3 --dataset BlogCatalog --test-size 0.4 --k 2
python train.py --index 0 3 --dataset BlogCatalog --test-size 0.4 --k 3
python train.py --index 0 3 --dataset BlogCatalog --test-size 0.4 --k 4
python train.py --index 0 3 --dataset BlogCatalog --test-size 0.4 --k 5
python train.py --index 0 3 --dataset BlogCatalog --test-size 0.4 --k 6
python train.py --index 0 3 --dataset BlogCatalog --test-size 0.4 --k 7
python train.py --index 0 3 --dataset BlogCatalog --test-size 0.4 --k 8
python train.py --index 0 3 --dataset BlogCatalog --test-size 0.4 --k 9
python train.py --index 0 3 --dataset BlogCatalog --test-size 0.4 --k 10
python train.py --index 0 3 --dataset BlogCatalog --test-size 0.6 --k 2
python train.py --index 0 3 --dataset BlogCatalog --test-size 0.6 --k 3
python train.py --index 0 3 --dataset BlogCatalog --test-size 0.6 --k 4
python train.py --index 0 3 --dataset BlogCatalog --test-size 0.6 --k 5
python train.py --index 0 3 --dataset BlogCatalog --test-size 0.6 --k 6
python train.py --index 0 3 --dataset BlogCatalog --test-size 0.6 --k 7
python train.py --index 0 3 --dataset BlogCatalog --test-size 0.6 --k 8
python train.py --index 0 3 --dataset BlogCatalog --test-size 0.6 --k 9
python train.py --index 0 3 --dataset BlogCatalog --test-size 0.6 --k 10
python train.py --index 0 3 --dataset BlogCatalog --test-size 0.8 --k 2
python train.py --index 0 3 --dataset BlogCatalog --test-size 0.8 --k 3
python train.py --index 0 3 --dataset BlogCatalog --test-size 0.8 --k 4
python train.py --index 0 3 --dataset BlogCatalog --test-size 0.8 --k 5
python train.py --index 0 3 --dataset BlogCatalog --test-size 0.8 --k 6
python train.py --index 0 3 --dataset BlogCatalog --test-size 0.8 --k 7
python train.py --index 0 3 --dataset BlogCatalog --test-size 0.8 --k 8
python train.py --index 0 3 --dataset BlogCatalog --test-size 0.8 --k 9
python train.py --index 0 3 --dataset BlogCatalog --test-size 0.8 --k 10
python train.py --index 0 3 --dataset pubmed --test-size 0.2 --k 2
python train.py --index 0 3 --dataset pubmed --test-size 0.2 --k 3
python train.py --index 0 3 --dataset pubmed --test-size 0.2 --k 4
python train.py --index 0 3 --dataset pubmed --test-size 0.2 --k 5
python train.py --index 0 3 --dataset pubmed --test-size 0.2 --k 6
python train.py --index 0 3 --dataset pubmed --test-size 0.2 --k 7
python train.py --index 0 3 --dataset pubmed --test-size 0.2 --k 8
python train.py --index 0 3 --dataset pubmed --test-size 0.2 --k 9
python train.py --index 0 3 --dataset pubmed --test-size 0.2 --k 10
python train.py --index 0 3 --dataset pubmed --test-size 0.4 --k 2
python train.py --index 0 3 --dataset pubmed --test-size 0.4 --k 3
python train.py --index 0 3 --dataset pubmed --test-size 0.4 --k 4
python train.py --index 0 3 --dataset pubmed --test-size 0.4 --k 5
python train.py --index 0 3 --dataset pubmed --test-size 0.4 --k 6
python train.py --index 0 3 --dataset pubmed --test-size 0.4 --k 7
python train.py --index 0 3 --dataset pubmed --test-size 0.4 --k 8
python train.py --index 0 3 --dataset pubmed --test-size 0.4 --k 9
python train.py --index 0 3 --dataset pubmed --test-size 0.4 --k 10
python train.py --index 0 3 --dataset pubmed --test-size 0.6 --k 2
python train.py --index 0 3 --dataset pubmed --test-size 0.6 --k 3
python train.py --index 0 3 --dataset pubmed --test-size 0.6 --k 4
python train.py --index 0 3 --dataset pubmed --test-size 0.6 --k 5
python train.py --index 0 3 --dataset pubmed --test-size 0.6 --k 6
python train.py --index 0 3 --dataset pubmed --test-size 0.6 --k 7
python train.py --index 0 3 --dataset pubmed --test-size 0.6 --k 8
python train.py --index 0 3 --dataset pubmed --test-size 0.6 --k 9
python train.py --index 0 3 --dataset pubmed --test-size 0.6 --k 10
python train.py --index 0 3 --dataset pubmed --test-size 0.8 --k 2
python train.py --index 0 3 --dataset pubmed --test-size 0.8 --k 3
python train.py --index 0 3 --dataset pubmed --test-size 0.8 --k 4
python train.py --index 0 3 --dataset pubmed --test-size 0.8 --k 5
python train.py --index 0 3 --dataset pubmed --test-size 0.8 --k 6
python train.py --index 0 3 --dataset pubmed --test-size 0.8 --k 7
python train.py --index 0 3 --dataset pubmed --test-size 0.8 --k 8
python train.py --index 0 3 --dataset pubmed --test-size 0.8 --k 9
python train.py --index 0 3 --dataset pubmed --test-size 0.8 --k 10
